#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌Failed. Prettier Check Failed. Run npm run format';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌Failed. ESLint Check Failed'. 
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌Failed Type check. Make the changes required above.'
    false;
)

# If everything passes... Now we can commit
echo '🤔 Alright, Code looks good to me. Trying to build now. '

npm run build ||
(
    echo '❌failed. Next build failed: View the errors above to see why. '
    false;
)

# If everything passes... Now we can commit
echo '✅You win this time. I am committing this now. '