#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


npm run check-format ||
(
    echo '❌Failed. Prettier Check Failed. Run npm run format';
    npm run format
    false;
)


# Check ESLint Standards
npm run check-lint ||
(
        echo '❌Failed. ESLint Check Failed'. 
        false; 
)

npm run build ||
(
    echo '❌failed. Next build failed: View the errors above to see why. '
    false;
)

# If everything passes... Now we can commit
echo '✅You win this time. I am committing this now. 'npo