name: Execução de teste

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Instalar e rodar dependecias
        run: npm install
      - name: Roda os testes
        run: npm run test
      - name: Lint
        run: npm run lint
          
